### ISSUE TITLE
Blog directory

### ISSUE THREAD

**Issue by impredicative** [dataplayer12/Fly-LSH#3]
Why is there a `blog` directory with duplicated files? Please consolidate the files and remove the duplicates.

**Comment by dataplayer12** [comment]
@impredicative thanks for pointing this out. The blog directory contains the code needed to reproduce results from my [blog](
https://medium.com/@jaiyamsharma/efficient-nearest-neighbors-inspired-by-the-fruit-fly-brain-6ef8fed416ee) explaining the original `FlyHash` algorithm. The code in the main directory is a much more developed version of the code in the blog dir, and contains newer algorithms not present in the blog dir. I have modified the readme of blog dir, stating this difference. If it is still a deal breaker, let me know and I will move that code to another repo.

**Comment by impredicative** [comment]
I would move it to another git branch or git tag named `blog` in this repo itself, and optionally link to that branch or tag from your blog. The code in the master branch should IMHO be clean.

**Comment by dataplayer12** [comment]
Thanks for the suggestion. It took me some time to get to this. The blog files are now in `blog` branch and the `master` has code corresponding only to the paper. Cheers!
