### ISSUE TITLE
Code incomprehension

### ISSUE THREAD

**Issue by 123123zz** [dataplayer12/Fly-LSH#5]
Hello author! I found that the code you gave just used the distance between images as labels, where findmap does not meet the requirements of image retrieval map. Moreover, the data set cifar10 was used for testing, and the hash value was extracted and saved as CSV file. According to the general map calculation method, the result retrieval accuracy was only 10%.

**Comment by dataplayer12** [comment]
Hi @123123zz , thanks for getting in touch. The euclidean distance is used as a performance metric in most of the publications on this topic. The performance of our code matches other publications on this topic. For example, please see the [issue](https://github.com/dataplayer12/Fly-LSH/issues/2) raised by the authors of a recent NeurIPS [paper](http://papers.nips.cc/paper/7302-fast-similarity-search-via-optimal-sparse-lifting.pdf). Please let me know if you have problems in reproducing these results.

**Comment by dataplayer12** [comment]
Hi @123123zz is your issue resolved? Did my response help you?

**Comment by 123123zz** [comment]
Hello author! I noticed that your paper mentions the use of the Cifar10 dataset, but in the general image retrieval, the searched MAP requires that the image's category label is the same, but it is not reflected in your code, and the hash code I will generate. Extracted, calculated map, the effect is very poor.

**Comment by dataplayer12** [comment]
Please see [table 1](https://arxiv.org/pdf/1812.01844.pdf) of our paper. We show results for five datasets, but not for CIFAR-10. The `Dataset` class in the code implements reading CIFAR-10 data but we do not claim any results on that dataset. In general, image retrieval methods use 2D convolution operations to preserve local features, whereas FlyHash and DenseFlyHash algorithms, as described in our paper, are applicable to high dimensional vectors, where the dimensions are all independent of each other. That being said, I have been working on a convolutional version of both these algorithms, which will be much more suitable for image retrieval. I guess I will update the repo.

**Comment by dataplayer12** [comment]
There has been no response from @123123zz in about 10 months, so I assume that the issue has been resolved.
