### ISSUE TITLE
m and k seems confused?

### ISSUE THREAD

**Issue by chansigit** [dataplayer12/Fly-LSH#8]
According to the definition of WTAHash in the paper, FlyHash should make the maximum become 1  in every block of length k, and make the other values 0 in the block. Finally FlyHash should produce a binary vector of length mk, where m values are 1.

But in the implementation of flylsh, I found the code actually do it in the opposite way: the block's length is m (hash_length) because the code find top hash_length elements in each row of the activation.
https://github.com/dataplayer12/Fly-LSH/blob/23f8975ce6970ea148935e3e59cca9c15e6019ac/lshutils.py#L446

Do I misunderstand the problem? If I am right, it is still not a very severe problem, you may fix it just by swap the parameters' names.

**Comment by dataplayer12** [comment]
Hi @chansigit 
Thank you for the feedback. Since this problem does not seem to impede the function of the program or your ability to use it, I have kept this issue on the back burner for the moment. Please give me some time to get back to you.

**Comment by chansigit** [comment]
No it doesn't affect the function of the program.  
I just hope to clarify my understanding of your codes and papers.
